// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

import { createMockClient } from '@/lib/mock-supabase-client';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const USE_MOCK = import.meta.env.VITE_USE_MOCK === 'true';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = USE_MOCK
  ? createMockClient() as any
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });

if (USE_MOCK) {
  console.info('--------------------------------------------------');
  console.info('🚧 APPLICATION RUNNING WITH MOCK DATABASE 🚧');
  console.info('--------------------------------------------------');
}